# Generated by Django 5.1.2 on 2024-10-21 02:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moodboard',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=26)),
                ('edges', models.ManyToManyField(blank=True, related_name='edges', to='data.edge')),
                ('nodes', models.ManyToManyField(blank=True, related_name='nodes', to='data.node')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
