# Generated by Django 5.1.2 on 2024-10-21 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='type',
        ),
    ]
